# Generated by Django 2.0.5 on 2019-04-03 21:32

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(default='1', max_length=10, verbose_name='权限')),
                ('lastTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后操作时间')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
                'verbose_name': '员工表',
            },
        ),
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=100)),
                ('hotelId', models.CharField(max_length=100)),
                ('modelId', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=100)),
                ('breakfast', models.CharField(max_length=150)),
                ('totalPrice', models.FloatField()),
                ('amount', models.FloatField()),
                ('commission', models.FloatField()),
                ('price', models.FloatField()),
                ('roomLeft', models.IntegerField()),
                ('crawler', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预定时间')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('insertDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='插入时间')),
                ('platform', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hotel',
                'ordering': ['id'],
                'verbose_name': '酒店',
            },
        ),
        migrations.CreateModel(
            name='UserQueryHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('hotelId', models.CharField(max_length=100)),
                ('crawler', models.SmallIntegerField(default=0)),
                ('priceStatus', models.SmallIntegerField(default=0)),
                ('start', models.CharField(max_length=50, verbose_name='开始时间')),
                ('end', models.CharField(max_length=50, verbose_name='结束时间')),
                ('modelId', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100, verbose_name='平台')),
            ],
            options={
                'db_table': 'queryhotel',
                'ordering': ['hotelId'],
                'verbose_name': '员工监控酒店列表',
            },
        ),
    ]
