# Generated by Django 2.0.5 on 2019-04-02 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('status', models.CharField(default='1', max_length=10, verbose_name='权限')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '员工表',
                'ordering': ['id'],
            },
        ),
    ]
