# Generated by Django 2.0.5 on 2019-04-02 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApi', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('hotelId', models.CharField(max_length=100)),
                ('crawler', models.SmallIntegerField(default=0)),
                ('start', models.CharField(max_length=50, verbose_name='开始时间')),
                ('end', models.CharField(max_length=50, verbose_name='结束时间')),
                ('modelId', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100, verbose_name='平台')),
            ],
            options={
                'verbose_name': '员工监控酒店列表',
                'db_table': 'queryhotel',
                'ordering': ['hotelId'],
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='lastTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后操作时间'),
        ),
    ]
